
# Windows専用 buildspec for CodeBuild
# Windows Server 2022 Container環境でのDockerイメージビルド
version: 0.2

env:
  shell: powershell

phases:
  pre_build:
    commands:
      - echo "Logging in to AWS ECR..."
      - echo "$env:AWS_ACCOUNT_ID + ".dkr.ecr." + $env:AWS_DEFAULT_REGION + ".amazonaws.com"
      - aws ecr get-login-password --region $env:AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ($env:AWS_ACCOUNT_ID + ".dkr.ecr." + $env:AWS_DEFAULT_REGION + ".amazonaws.com")

  build:
    commands:
      - echo "Build phase started on $(Get-Date)"
      - Copy-Item -Path "execution\countdown.exe" -Destination "image\"
      - Set-Location -Path "image"
      - docker build -t "$env:REPOSITORY_URI:latest" .
      - docker build -t "$env:REPOSITORY_URI:$env:IMAGE_TAG" .
      - echo "Build completed on $(Get-Date)"

  post_build:
    commands:
      - echo "Post build phase started on $(Get-Date)"
      - docker push "$env:REPOSITORY_URI:latest"
      - docker push "$env:REPOSITORY_URI:$env:IMAGE_TAG"
      - echo "Creating image definitions file..."
      - |
          $json = '[{"name":"countdown-container","imageUri":"' + $env:REPOSITORY_URI + ':' + $env:IMAGE_TAG + '"}]'
          Set-Content -Path imagedefinitions.json -Value $json
      - echo "Image definitions file created:"
      - Get-Content -Path imagedefinitions.json
      - echo "Post build completed on $(Get-Date)"
artifacts:
  files:
    - imagedefinitions.json
    - '**/*'
  name: BuildArtifact
