version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - REPOSITORY_URI_BASE=$(echo $REPOSITORY_URI | cut -d'/' -f1)
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - echo Repository URI base is $REPOSITORY_URI_BASE
      - echo Image tag is $IMAGE_TAG
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building Windows Docker image...
      # Windows executable should already be built in the source
      - cd image
      - docker build -t $REPOSITORY_URI:latest .
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Build completed on `date`
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"countdown-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - '**/*'
