# Windows専用 buildspec for CodeBuild
# Windows Server 2019 Container環境でのDockerイメージビルド

version: 0.2

phases:
  pre_build:
    commands:
      - echo "Build started on %date% %time%"
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - echo "Logging in to ECR repository %REPOSITORY_URI%"
      - aws ecr get-login-password --region ap-northeast-1 > ecr_password.txt
      - set /p ECR_PASSWORD=<ecr_password.txt
      - echo %REPOSITORY_URI% > temp_uri.txt
      - powershell -Command "(Get-Content temp_uri.txt).Split('/')[0]" > ecr_registry.txt
      - set /p ECR_REGISTRY=<ecr_registry.txt
      - echo %ECR_PASSWORD% | docker login --username AWS --password-stdin %ECR_REGISTRY%
      - del ecr_password.txt
      - del temp_uri.txt
      - del ecr_registry.txt
      - echo "Repository login completed"
      - set IMAGE_TAG=%CODEBUILD_RESOLVED_SOURCE_VERSION:~0,7%
      - echo "Image tag will be %IMAGE_TAG%"
      
  build:
    commands:
      - echo "Build phase started on %date% %time%"
      - echo "Building Windows Docker image..."
      - echo "Current directory:"
      - dir
      - echo "Checking execution directory:"
      - dir execution
      - echo "Using pre-built countdown.exe..."
      - cd execution
      - 'if not exist "countdown.exe" (echo "Error: countdown.exe not found!" && exit /b 1)'
      - echo "countdown.exe found, copying to image directory..."
      - copy countdown.exe ..\image\
      - cd ..\image
      - echo "Building Docker image..."
      - docker build -t %REPOSITORY_URI%:latest .
      - docker build -t %REPOSITORY_URI%:%IMAGE_TAG% .
      - echo "Build completed on %date% %time%"
      
  post_build:
    commands:
      - echo "Post build phase started on %date% %time%"
      - echo "Pushing Docker images to ECR..."
      - docker push %REPOSITORY_URI%:latest
      - docker push %REPOSITORY_URI%:%IMAGE_TAG%
      - echo "Creating image definitions file..."
      - echo [{"name":"countdown-container","imageUri":"%REPOSITORY_URI%:%IMAGE_TAG%"}] > imagedefinitions.json
      - echo "Image definitions file created:"
      - type imagedefinitions.json
      - echo "Post build completed on %date% %time%"

artifacts:
  files:
    - imagedefinitions.json
    - '**/*'
  name: BuildArtifact
